# Generated by Django 2.2.4 on 2019-08-18 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 16, 31, 47, 69861), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
