# Generated by Django 2.2.4 on 2019-08-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20190818_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Name')),
                ('contact_address', models.TextField(verbose_name='Address')),
                ('contact_added', models.DateTimeField(default=datetime.datetime(2019, 8, 18, 16, 38, 35, 265937), verbose_name='Date Added/Updated')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 16, 38, 35, 265436), verbose_name='Date Published'),
        ),
    ]
