# Generated by Django 2.2.4 on 2019-08-18 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_auto_20190818_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='contact_number',
            field=models.IntegerField(default='8800000000000', verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='contact_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 16, 41, 59, 656259), verbose_name='Date Added/Updated'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 16, 41, 59, 655283), verbose_name='Date Published'),
        ),
    ]
