# Generated by Django 2.2.4 on 2019-08-21 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_auto_20190818_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='contact_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 14, 3, 37, 376512), verbose_name='Date Added/Updated'),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='contact_number',
            field=models.CharField(default='8800000000000', max_length=20, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 14, 3, 37, 375511), verbose_name='Date Published'),
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series_name', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('category_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='webApp.TutorialCategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_series_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='webApp.TutorialSeries', verbose_name='Series'),
        ),
    ]
